version: 0.2

artifacts:
  files:
    - '**/*'
    - scripts/*
    - dog-1.jpg
  name: s3-to-s3-latest-build.zip
  discard-paths: no

phases:
  install: 
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing node"
  pre_build:
    commands:
      - echo "In the prebuild phase"
  build:
    commands:
      - echo "In the build phase"
  post_build:
    commands:
      - echo "In the postbuild phase"