version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing node"
  pre_build:
    commands:
      - echo "In the prebuild phase"
  build:
    commands:
      - echo "In the build phase"
  post_build:
    commands:
      - echo "In the postbuild phase"